services:
  shop:
    build: 
      context: .
      dockerfile: ./apps/shop/Dockerfile
      target: development
    command: npm run start:dev shop
    env_file:
      - ./apps/shop/.env
    depends_on:
      - email
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:  
      - '3000:3000'
  email:
    build: 
      context: .
      dockerfile: ./apps/email/Dockerfile
      target: development
    command: npm run start:dev email
    env_file:
      - ./apps/email/.env 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - '5672:5672'